name: MineChem
version: '${project.version}'
main: com.github.justadeni.minechem.MineChem
api-version: 1.19
load: STARTUP
depend: [NBTAPI]
commands:
  minechem:
    usage: /minechem <subcommand> <id>
